Console.WriteLine("Введите x первой точки ");
double x1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите y первой точки ");
double y1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите z первой точки ");
double z1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите x второй точки ");
double x2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите y второй точки ");
double y2 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите z второй точки ");
double z2 = Convert.ToDouble(Console.ReadLine());
double r = Math.Sqrt((x2 - x1)*(x2 - x1) + (y2 - y1)*(y2 - y1)+(z2-z1)*(z2-z1));
Console.WriteLine($"{r}");
